application: gimpify
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img
  static_dir: static/img

- url: /.*
  script: gimpify.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: "2.6"

- name: PIL
  version: "1.1.7"
